# Generated by Django 5.2.9 on 2025-12-03 12:31

import club_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(validators=[club_management.models.valider_age])),
                ('phone_number', models.CharField(max_length=8, validators=[club_management.models.validate_phone])),
            ],
        ),
    ]
