# Generated by Django 5.2.9 on 2025-12-03 15:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('act_Code', models.IntegerField(primary_key=True, serialize=False)),
                ('act_Name', models.CharField(max_length=255)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('Member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.member')),
                ('act_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.activity')),
            ],
        ),
    ]
