# Generated by Django 5.2.9 on 2025-12-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0002_activity_inscription'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='activity',
        ),
        migrations.AlterModelTable(
            name='inscription',
            table='inscription',
        ),
        migrations.AlterModelTable(
            name='member',
            table='member',
        ),
    ]
