# Generated by Django 5.2.9 on 2025-12-03 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0003_alter_activity_table_alter_inscription_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='activity',
            table='club_activity',
        ),
        migrations.AlterModelTable(
            name='inscription',
            table='club_inscription',
        ),
        migrations.AlterModelTable(
            name='member',
            table='club_member',
        ),
    ]
