# Generated by Django 5.2.9 on 2025-12-03 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0004_alter_activity_table_alter_inscription_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscription',
            old_name='Member_id',
            new_name='member_Id',
        ),
        migrations.AlterUniqueTogether(
            name='inscription',
            unique_together={('member_Id', 'act_Code')},
        ),
    ]
