# Generated by Django 5.2.9 on 2025-12-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0005_rename_member_id_inscription_member_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='act_Code',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='member_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
